// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#ifndef __BINDINGS_TEST_H
#define __BINDINGS_TEST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct test_string_t {
  uint8_t*ptr;
  size_t len;
} test_string_t;

typedef struct tests_component_types_point_t {
  int32_t   x;
  int32_t   y;
} tests_component_types_point_t;

typedef struct tests_component_types_entity_t {
  int32_t   id;
  test_string_t   name;
  tests_component_types_point_t   position;
} tests_component_types_entity_t;

typedef uint8_t tests_component_types_status_t;

#define TESTS_COMPONENT_TYPES_STATUS_ACTIVE 0
#define TESTS_COMPONENT_TYPES_STATUS_INACTIVE 1
#define TESTS_COMPONENT_TYPES_STATUS_PENDING 2

typedef uint8_t tests_component_types_permission_t;

#define TESTS_COMPONENT_TYPES_PERMISSION_READ (1 << 0)
#define TESTS_COMPONENT_TYPES_PERMISSION_WRITE (1 << 1)
#define TESTS_COMPONENT_TYPES_PERMISSION_EXECUTE (1 << 2)

typedef struct tests_component_types_value_or_error_t {
  uint8_t tag;
  union {
    test_string_t     value;
    test_string_t     error;
  } val;
} tests_component_types_value_or_error_t;

#define TESTS_COMPONENT_TYPES_VALUE_OR_ERROR_VALUE 0
#define TESTS_COMPONENT_TYPES_VALUE_OR_ERROR_ERROR 1

typedef struct tests_component_host_counter_own_counter_t {
  int32_t __handle;
} tests_component_host_counter_own_counter_t;

typedef struct tests_component_host_counter_borrow_counter_t {
  int32_t __handle;
} tests_component_host_counter_borrow_counter_t;

typedef tests_component_types_entity_t test_entity_t;

typedef tests_component_types_point_t test_point_t;

typedef tests_component_types_status_t test_status_t;

typedef tests_component_types_permission_t test_permission_t;

typedef tests_component_types_value_or_error_t test_value_or_error_t;

typedef struct {
  test_entity_t *ptr;
  size_t len;
} test_list_entity_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} test_list_u32_t;

typedef struct {
  test_list_u32_t *ptr;
  size_t len;
} test_list_list_u32_t;

typedef struct {
  int32_t *ptr;
  size_t len;
} test_list_s32_t;

typedef struct {
  test_status_t *ptr;
  size_t len;
} test_list_status_t;

typedef struct {
  test_permission_t *ptr;
  size_t len;
} test_list_permission_t;

typedef struct {
  bool is_err;
  union {
    int32_t ok;
    test_string_t err;
  } val;
} test_result_s32_string_t;

typedef struct {
  bool is_some;
  int32_t val;
} test_option_s32_t;

// Imported Functions from `tests:component/host-counter@0.1.0`
extern tests_component_host_counter_own_counter_t tests_component_host_counter_constructor_counter(int32_t initial);
extern int32_t tests_component_host_counter_method_counter_increment(tests_component_host_counter_borrow_counter_t self, int32_t by);
extern int32_t tests_component_host_counter_method_counter_value(tests_component_host_counter_borrow_counter_t self);
extern int32_t tests_component_host_counter_static_counter_merge(int32_t a, int32_t b);

// Imported Functions from `test`
extern void test_callback(void);
extern void test_callback_combine_string(test_string_t *s1, test_string_t *s2, test_string_t *ret);
extern void test_get_host_entity(test_entity_t *ret);

// Exported Functions from `test`
void exports_test_register_entity(test_entity_t *e);
void exports_test_register_entities(test_list_entity_t *e);
void exports_test_get_entity(int32_t id, test_entity_t *ret);
void exports_test_get_entities(test_list_entity_t *ret);
void exports_test_set_flag(bool flag);
bool exports_test_get_flag(void);
void exports_test_get_host_entity_description(test_string_t *ret);
uint32_t exports_test_sum_nested_list(test_list_list_u32_t *nested);
void exports_test_host_callback(void);
void exports_test_host_combine_string(test_string_t *s1, test_string_t *s2, test_string_t *ret);
void exports_test_combine_string(test_string_t *s1, test_string_t *s2, test_string_t *ret);
void exports_test_accept_string(test_string_t *s);
void exports_test_return_string(uint32_t length, test_string_t *ret);
int32_t exports_test_use_counter(int32_t initial, int32_t by);
int32_t exports_test_use_static_merge(int32_t a, int32_t b);
uint8_t exports_test_add_u8(uint8_t x, uint8_t y);
int8_t exports_test_add_s8(int8_t x, int8_t y);
uint16_t exports_test_add_u16(uint16_t x, uint16_t y);
int16_t exports_test_add_s16(int16_t x, int16_t y);
uint32_t exports_test_add_u32(uint32_t x, uint32_t y);
int32_t exports_test_add_s32(int32_t x, int32_t y);
uint64_t exports_test_add_u64(uint64_t x, uint64_t y);
int64_t exports_test_add_s64(int64_t x, int64_t y);
float exports_test_add_f32(float x, float y);
double exports_test_add_f64(double x, double y);
void exports_test_add_point(test_point_t *p1, test_point_t *p2, test_point_t *ret);
void exports_test_uppercase(test_string_t *s, test_string_t *ret);
void exports_test_multiply_list(test_list_s32_t *list, int32_t factor, test_list_s32_t *ret);
test_status_t exports_test_return_status(test_status_t status);
void exports_test_return_status_list(test_list_status_t *statuses, test_list_status_t *ret);
test_permission_t exports_test_return_permission(test_permission_t permission);
void exports_test_return_permission_list(test_list_permission_t *permissions, test_list_permission_t *ret);
bool exports_test_safe_divide(int32_t a, int32_t b, int32_t *ret, test_string_t *err);
void exports_test_divide_variant(int32_t a, int32_t b, test_value_or_error_t *ret);
void exports_test_variant_tag(test_value_or_error_t *v, test_string_t *ret);
bool exports_test_maybe_double(int32_t *maybe_x, int32_t *ret);

// Helper Functions

void tests_component_types_entity_free(tests_component_types_entity_t *ptr);

void tests_component_types_value_or_error_free(tests_component_types_value_or_error_t *ptr);

extern void tests_component_host_counter_counter_drop_own(tests_component_host_counter_own_counter_t handle);

extern tests_component_host_counter_borrow_counter_t tests_component_host_counter_borrow_counter(tests_component_host_counter_own_counter_t handle);

void test_entity_free(test_entity_t *ptr);

void test_value_or_error_free(test_value_or_error_t *ptr);

void test_list_entity_free(test_list_entity_t *ptr);

void test_list_u32_free(test_list_u32_t *ptr);

void test_list_list_u32_free(test_list_list_u32_t *ptr);

void test_list_s32_free(test_list_s32_t *ptr);

void test_list_status_free(test_list_status_t *ptr);

void test_list_permission_free(test_list_permission_t *ptr);

void test_result_s32_string_free(test_result_s32_string_t *ptr);

void test_option_s32_free(test_option_s32_t *ptr);

// Transfers ownership of `s` into the string `ret`
void test_string_set(test_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void test_string_dup(test_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void test_string_free(test_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
