// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#include "test.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `tests:component/host-counter@0.1.0`

__attribute__((__import_module__("tests:component/host-counter@0.1.0"), __import_name__("[constructor]counter")))
extern int32_t __wasm_import_tests_component_host_counter_constructor_counter(int32_t);

__attribute__((__import_module__("tests:component/host-counter@0.1.0"), __import_name__("[method]counter.increment")))
extern int32_t __wasm_import_tests_component_host_counter_method_counter_increment(int32_t, int32_t);

__attribute__((__import_module__("tests:component/host-counter@0.1.0"), __import_name__("[method]counter.value")))
extern int32_t __wasm_import_tests_component_host_counter_method_counter_value(int32_t);

__attribute__((__import_module__("tests:component/host-counter@0.1.0"), __import_name__("[static]counter.merge")))
extern int32_t __wasm_import_tests_component_host_counter_static_counter_merge(int32_t, int32_t);

// Imported Functions from `test`

__attribute__((__import_module__("$root"), __import_name__("callback")))
extern void __wasm_import_test_callback(void);

__attribute__((__import_module__("$root"), __import_name__("callback-combine-string")))
extern void __wasm_import_test_callback_combine_string(uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("$root"), __import_name__("get-host-entity")))
extern void __wasm_import_test_get_host_entity(uint8_t *);

// Exported Functions from `test`



__attribute__((__weak__, __export_name__("cabi_post_get-entity")))
void __wasm_export_exports_test_get_entity_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + sizeof(void*))));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_get-entities")))
void __wasm_export_exports_test_get_entities_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (8+3*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + sizeof(void*))));
      }
    }
    free(ptr);
  }
}



__attribute__((__weak__, __export_name__("cabi_post_get-host-entity-description")))
void __wasm_export_exports_test_get_host_entity_description_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}



__attribute__((__weak__, __export_name__("cabi_post_host-combine-string")))
void __wasm_export_exports_test_host_combine_string_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_combine-string")))
void __wasm_export_exports_test_combine_string_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}


__attribute__((__weak__, __export_name__("cabi_post_return-string")))
void __wasm_export_exports_test_return_string_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}














__attribute__((__weak__, __export_name__("cabi_post_uppercase")))
void __wasm_export_exports_test_uppercase_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_multiply-list")))
void __wasm_export_exports_test_multiply_list_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 4;
      (void) base;
    }
    free(ptr);
  }
}


__attribute__((__weak__, __export_name__("cabi_post_return-status-list")))
void __wasm_export_exports_test_return_status_list_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 1;
      (void) base;
    }
    free(ptr);
  }
}


__attribute__((__weak__, __export_name__("cabi_post_return-permission-list")))
void __wasm_export_exports_test_return_permission_list_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 1;
      (void) base;
    }
    free(ptr);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_safe-divide")))
void __wasm_export_exports_test_safe_divide_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_divide-variant")))
void __wasm_export_exports_test_divide_variant_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_variant-tag")))
void __wasm_export_exports_test_variant_tag_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}


// Exported Functions from `tests:component/accumulator-api@0.1.0`




__attribute__((__weak__, __export_name__("cabi_post_tests:component/accumulator-api@0.1.0#describe")))
void __wasm_export_exports_tests_component_accumulator_api_describe_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void tests_component_types_entity_free(tests_component_types_entity_t *ptr) {
  test_string_free(&ptr->name);
}

void tests_component_types_value_or_error_free(tests_component_types_value_or_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      test_string_free(&ptr->val.value);
      break;
    }
    case 1: {
      test_string_free(&ptr->val.error);
      break;
    }
  }
}

__attribute__((__import_module__("tests:component/host-counter@0.1.0"), __import_name__("[resource-drop]counter")))
extern void __wasm_import_tests_component_host_counter_counter_drop(int32_t handle);

void tests_component_host_counter_counter_drop_own(tests_component_host_counter_own_counter_t handle) {
  __wasm_import_tests_component_host_counter_counter_drop(handle.__handle);
}

tests_component_host_counter_borrow_counter_t tests_component_host_counter_borrow_counter(tests_component_host_counter_own_counter_t arg) {
  return (tests_component_host_counter_borrow_counter_t) { arg.__handle };
}

void test_entity_free(test_entity_t *ptr) {
  tests_component_types_entity_free(ptr);
}

void test_value_or_error_free(test_value_or_error_t *ptr) {
  tests_component_types_value_or_error_free(ptr);
}

void test_list_entity_free(test_list_entity_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    test_entity_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      test_entity_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void test_list_u32_free(test_list_u32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void test_list_list_u32_free(test_list_list_u32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    test_list_u32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      test_list_u32_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void test_list_s32_free(test_list_s32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    int32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void test_list_status_free(test_list_status_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    test_status_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void test_list_permission_free(test_list_permission_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    test_permission_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void test_result_s32_string_free(test_result_s32_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    test_string_free(&ptr->val.err);
  }
}

void test_option_s32_free(test_option_s32_t *ptr) {
  if (ptr->is_some) {
  }
}

__attribute__((__import_module__("[export]tests:component/accumulator-api@0.1.0"), __import_name__("[resource-drop]accumulator")))
extern void __wasm_import_exports_tests_component_accumulator_api_accumulator_drop(int32_t handle);

void exports_tests_component_accumulator_api_accumulator_drop_own(exports_tests_component_accumulator_api_own_accumulator_t handle) {
  __wasm_import_exports_tests_component_accumulator_api_accumulator_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]tests:component/accumulator-api@0.1.0"), __import_name__("[resource-new]accumulator")))
extern int32_t __wasm_import_exports_tests_component_accumulator_api_accumulator_new(int32_t);

__attribute__((__import_module__("[export]tests:component/accumulator-api@0.1.0"), __import_name__("[resource-rep]accumulator")))
extern int32_t __wasm_import_exports_tests_component_accumulator_api_accumulator_rep(int32_t);

exports_tests_component_accumulator_api_own_accumulator_t exports_tests_component_accumulator_api_accumulator_new(exports_tests_component_accumulator_api_accumulator_t *rep) {
  return (exports_tests_component_accumulator_api_own_accumulator_t) { __wasm_import_exports_tests_component_accumulator_api_accumulator_new((int32_t) rep) };
}

exports_tests_component_accumulator_api_accumulator_t* exports_tests_component_accumulator_api_accumulator_rep(exports_tests_component_accumulator_api_own_accumulator_t handle) {
  return (exports_tests_component_accumulator_api_accumulator_t*) __wasm_import_exports_tests_component_accumulator_api_accumulator_rep(handle.__handle);
}

__attribute__((__export_name__("tests:component/accumulator-api@0.1.0#[dtor]accumulator")))
void __wasm_export_exports_tests_component_accumulator_api_accumulator_dtor(exports_tests_component_accumulator_api_accumulator_t* arg) {
  exports_tests_component_accumulator_api_accumulator_destructor(arg);
}

void test_string_set(test_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void test_string_dup(test_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void test_string_free(test_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(8+3*sizeof(void*))];

tests_component_host_counter_own_counter_t tests_component_host_counter_constructor_counter(int32_t initial) {
  int32_t ret = __wasm_import_tests_component_host_counter_constructor_counter(initial);
  return (tests_component_host_counter_own_counter_t) { ret };
}

int32_t tests_component_host_counter_method_counter_increment(tests_component_host_counter_borrow_counter_t self, int32_t by) {
  int32_t ret = __wasm_import_tests_component_host_counter_method_counter_increment((self).__handle, by);
  return ret;
}

int32_t tests_component_host_counter_method_counter_value(tests_component_host_counter_borrow_counter_t self) {
  int32_t ret = __wasm_import_tests_component_host_counter_method_counter_value((self).__handle);
  return ret;
}

int32_t tests_component_host_counter_static_counter_merge(int32_t a, int32_t b) {
  int32_t ret = __wasm_import_tests_component_host_counter_static_counter_merge(a, b);
  return ret;
}

void test_callback(void) {
  __wasm_import_test_callback();
}

void test_callback_combine_string(test_string_t *s1, test_string_t *s2, test_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_test_callback_combine_string((uint8_t *) (*s1).ptr, (*s1).len, (uint8_t *) (*s2).ptr, (*s2).len, ptr);
  *ret = (test_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void test_get_host_entity(test_entity_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(8+3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_test_get_host_entity(ptr);
  *ret = (tests_component_types_entity_t) {
    (int32_t) *((int32_t*) (ptr + 0)),
    (test_string_t) (test_string_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) },
    (tests_component_types_point_t) (tests_component_types_point_t) {
      (int32_t) *((int32_t*) (ptr + (3*sizeof(void*)))),
      (int32_t) *((int32_t*) (ptr + (4+3*sizeof(void*)))),
    },
  };
}

__attribute__((__export_name__("register-entity")))
void __wasm_export_exports_test_register_entity(int32_t arg, uint8_t * arg0, size_t arg1, int32_t arg2, int32_t arg3) {
  test_entity_t arg4 = (tests_component_types_entity_t) {
    (int32_t) arg,
    (test_string_t) (test_string_t) { (uint8_t*)(arg0), (arg1) },
    (tests_component_types_point_t) (tests_component_types_point_t) {
      (int32_t) arg2,
      (int32_t) arg3,
    },
  };
  exports_test_register_entity(&arg4);
}

__attribute__((__export_name__("register-entities")))
void __wasm_export_exports_test_register_entities(uint8_t * arg, size_t arg0) {
  test_list_entity_t arg1 = (test_list_entity_t) { (test_entity_t*)(arg), (arg0) };
  exports_test_register_entities(&arg1);
}

__attribute__((__export_name__("get-entity")))
uint8_t * __wasm_export_exports_test_get_entity(int32_t arg) {
  test_entity_t ret;
  exports_test_get_entity(arg, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((int32_t*)(ptr + 0)) = (ret).id;
  *((size_t*)(ptr + (2*sizeof(void*)))) = ((ret).name).len;
  *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) ((ret).name).ptr;
  *((int32_t*)(ptr + (3*sizeof(void*)))) = ((ret).position).x;
  *((int32_t*)(ptr + (4+3*sizeof(void*)))) = ((ret).position).y;
  return ptr;
}

__attribute__((__export_name__("get-entities")))
uint8_t * __wasm_export_exports_test_get_entities(void) {
  test_list_entity_t ret;
  exports_test_get_entities(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("set-flag")))
void __wasm_export_exports_test_set_flag(int32_t arg) {
  exports_test_set_flag(arg);
}

__attribute__((__export_name__("get-flag")))
int32_t __wasm_export_exports_test_get_flag(void) {
  bool ret = exports_test_get_flag();
  return ret;
}

__attribute__((__export_name__("get-host-entity-description")))
uint8_t * __wasm_export_exports_test_get_host_entity_description(void) {
  test_string_t ret;
  exports_test_get_host_entity_description(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("sum-nested-list")))
int32_t __wasm_export_exports_test_sum_nested_list(uint8_t * arg, size_t arg0) {
  test_list_list_u32_t arg1 = (test_list_list_u32_t) { (test_list_u32_t*)(arg), (arg0) };
  uint32_t ret = exports_test_sum_nested_list(&arg1);
  return (int32_t) (ret);
}

__attribute__((__export_name__("host-callback")))
void __wasm_export_exports_test_host_callback(void) {
  exports_test_host_callback();
}

__attribute__((__export_name__("host-combine-string")))
uint8_t * __wasm_export_exports_test_host_combine_string(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  test_string_t arg3 = (test_string_t) { (uint8_t*)(arg), (arg0) };
  test_string_t arg4 = (test_string_t) { (uint8_t*)(arg1), (arg2) };
  test_string_t ret;
  exports_test_host_combine_string(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("combine-string")))
uint8_t * __wasm_export_exports_test_combine_string(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  test_string_t arg3 = (test_string_t) { (uint8_t*)(arg), (arg0) };
  test_string_t arg4 = (test_string_t) { (uint8_t*)(arg1), (arg2) };
  test_string_t ret;
  exports_test_combine_string(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("accept-string")))
void __wasm_export_exports_test_accept_string(uint8_t * arg, size_t arg0) {
  test_string_t arg1 = (test_string_t) { (uint8_t*)(arg), (arg0) };
  exports_test_accept_string(&arg1);
}

__attribute__((__export_name__("return-string")))
uint8_t * __wasm_export_exports_test_return_string(int32_t arg) {
  test_string_t ret;
  exports_test_return_string((uint32_t) (arg), &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("use-counter")))
int32_t __wasm_export_exports_test_use_counter(int32_t arg, int32_t arg0) {
  int32_t ret = exports_test_use_counter(arg, arg0);
  return ret;
}

__attribute__((__export_name__("use-static-merge")))
int32_t __wasm_export_exports_test_use_static_merge(int32_t arg, int32_t arg0) {
  int32_t ret = exports_test_use_static_merge(arg, arg0);
  return ret;
}

__attribute__((__export_name__("add-u8")))
int32_t __wasm_export_exports_test_add_u8(int32_t arg, int32_t arg0) {
  uint8_t ret = exports_test_add_u8((uint8_t) (arg), (uint8_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("add-s8")))
int32_t __wasm_export_exports_test_add_s8(int32_t arg, int32_t arg0) {
  int8_t ret = exports_test_add_s8((int8_t) (arg), (int8_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("add-u16")))
int32_t __wasm_export_exports_test_add_u16(int32_t arg, int32_t arg0) {
  uint16_t ret = exports_test_add_u16((uint16_t) (arg), (uint16_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("add-s16")))
int32_t __wasm_export_exports_test_add_s16(int32_t arg, int32_t arg0) {
  int16_t ret = exports_test_add_s16((int16_t) (arg), (int16_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("add-u32")))
int32_t __wasm_export_exports_test_add_u32(int32_t arg, int32_t arg0) {
  uint32_t ret = exports_test_add_u32((uint32_t) (arg), (uint32_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("add-s32")))
int32_t __wasm_export_exports_test_add_s32(int32_t arg, int32_t arg0) {
  int32_t ret = exports_test_add_s32(arg, arg0);
  return ret;
}

__attribute__((__export_name__("add-u64")))
int64_t __wasm_export_exports_test_add_u64(int64_t arg, int64_t arg0) {
  uint64_t ret = exports_test_add_u64((uint64_t) (arg), (uint64_t) (arg0));
  return (int64_t) (ret);
}

__attribute__((__export_name__("add-s64")))
int64_t __wasm_export_exports_test_add_s64(int64_t arg, int64_t arg0) {
  int64_t ret = exports_test_add_s64(arg, arg0);
  return ret;
}

__attribute__((__export_name__("add-f32")))
float __wasm_export_exports_test_add_f32(float arg, float arg0) {
  float ret = exports_test_add_f32(arg, arg0);
  return ret;
}

__attribute__((__export_name__("add-f64")))
double __wasm_export_exports_test_add_f64(double arg, double arg0) {
  double ret = exports_test_add_f64(arg, arg0);
  return ret;
}

__attribute__((__export_name__("add-point")))
uint8_t * __wasm_export_exports_test_add_point(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2) {
  test_point_t arg3 = (tests_component_types_point_t) {
    (int32_t) arg,
    (int32_t) arg0,
  };
  test_point_t arg4 = (tests_component_types_point_t) {
    (int32_t) arg1,
    (int32_t) arg2,
  };
  test_point_t ret;
  exports_test_add_point(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((int32_t*)(ptr + 0)) = (ret).x;
  *((int32_t*)(ptr + 4)) = (ret).y;
  return ptr;
}

__attribute__((__export_name__("uppercase")))
uint8_t * __wasm_export_exports_test_uppercase(uint8_t * arg, size_t arg0) {
  test_string_t arg1 = (test_string_t) { (uint8_t*)(arg), (arg0) };
  test_string_t ret;
  exports_test_uppercase(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("multiply-list")))
uint8_t * __wasm_export_exports_test_multiply_list(uint8_t * arg, size_t arg0, int32_t arg1) {
  test_list_s32_t arg2 = (test_list_s32_t) { (int32_t*)(arg), (arg0) };
  test_list_s32_t ret;
  exports_test_multiply_list(&arg2, arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("return-status")))
int32_t __wasm_export_exports_test_return_status(int32_t arg) {
  test_status_t ret = exports_test_return_status(arg);
  return (int32_t) ret;
}

__attribute__((__export_name__("return-status-list")))
uint8_t * __wasm_export_exports_test_return_status_list(uint8_t * arg, size_t arg0) {
  test_list_status_t arg1 = (test_list_status_t) { (test_status_t*)(arg), (arg0) };
  test_list_status_t ret;
  exports_test_return_status_list(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("return-permission")))
int32_t __wasm_export_exports_test_return_permission(int32_t arg) {
  test_permission_t ret = exports_test_return_permission(arg);
  return ret;
}

__attribute__((__export_name__("return-permission-list")))
uint8_t * __wasm_export_exports_test_return_permission_list(uint8_t * arg, size_t arg0) {
  test_list_permission_t arg1 = (test_list_permission_t) { (test_permission_t*)(arg), (arg0) };
  test_list_permission_t ret;
  exports_test_return_permission_list(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("safe-divide")))
uint8_t * __wasm_export_exports_test_safe_divide(int32_t arg, int32_t arg0) {
  test_result_s32_string_t ret;
  int32_t ok;
  test_string_t err;
  ret.is_err = !exports_test_safe_divide(arg, arg0, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const test_string_t *payload1 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload1).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload1).ptr;
  } else {
    const int32_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + sizeof(void*))) = *payload;
  }
  return ptr;
}

__attribute__((__export_name__("divide-variant")))
uint8_t * __wasm_export_exports_test_divide_variant(int32_t arg, int32_t arg0) {
  test_value_or_error_t ret;
  exports_test_divide_variant(arg, arg0, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  switch ((int32_t) (ret).tag) {
    case 0: {
      const test_string_t *payload = &(ret).val.value;
      *((int8_t*)(ptr + 0)) = 0;
      *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload).len;
      *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload).ptr;
      break;
    }
    case 1: {
      const test_string_t *payload1 = &(ret).val.error;
      *((int8_t*)(ptr + 0)) = 1;
      *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload1).len;
      *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload1).ptr;
      break;
    }
  }
  return ptr;
}

__attribute__((__export_name__("variant-tag")))
uint8_t * __wasm_export_exports_test_variant_tag(int32_t arg, uint8_t * arg0, size_t arg1) {
  tests_component_types_value_or_error_t variant;
  variant.tag = arg;
  switch ((int32_t) variant.tag) {
    case 0: {
      variant.val.value = (test_string_t) { (uint8_t*)(arg0), (arg1) };
      break;
    }
    case 1: {
      variant.val.error = (test_string_t) { (uint8_t*)(arg0), (arg1) };
      break;
    }
  }
  test_value_or_error_t arg2 = variant;
  test_string_t ret;
  exports_test_variant_tag(&arg2, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("maybe-double")))
uint8_t * __wasm_export_exports_test_maybe_double(int32_t arg, int32_t arg0) {
  test_option_s32_t option;
  switch (arg) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = arg0;
      break;
    }
  }
  int32_t val;
  bool ret = exports_test_maybe_double(option.is_some ? &(option.val) : NULL, &val);

  test_option_s32_t ret1;
  ret1.is_some = ret;
  ret1.val = val;
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret1).is_some) {
    const int32_t *payload2 = &(ret1).val;
    *((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 4)) = *payload2;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("tests:component/accumulator-api@0.1.0#[constructor]accumulator")))
int32_t __wasm_export_exports_tests_component_accumulator_api_constructor_accumulator(int32_t arg) {
  exports_tests_component_accumulator_api_own_accumulator_t ret = exports_tests_component_accumulator_api_constructor_accumulator(arg);
  return (ret).__handle;
}

__attribute__((__export_name__("tests:component/accumulator-api@0.1.0#[method]accumulator.add")))
int32_t __wasm_export_exports_tests_component_accumulator_api_method_accumulator_add(uint8_t * arg, int32_t arg0) {
  int32_t ret = exports_tests_component_accumulator_api_method_accumulator_add(((exports_tests_component_accumulator_api_accumulator_t*) arg), arg0);
  return ret;
}

__attribute__((__export_name__("tests:component/accumulator-api@0.1.0#[static]accumulator.combine")))
int32_t __wasm_export_exports_tests_component_accumulator_api_static_accumulator_combine(int32_t arg, int32_t arg0) {
  int32_t ret = exports_tests_component_accumulator_api_static_accumulator_combine(arg, arg0);
  return ret;
}

__attribute__((__export_name__("tests:component/accumulator-api@0.1.0#describe")))
uint8_t * __wasm_export_exports_tests_component_accumulator_api_describe(void) {
  test_string_t ret;
  exports_tests_component_accumulator_api_describe(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_test(void);
void __component_type_object_force_link_test_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_test();
}
